---
title: "IS 590R Function"
output: html_document
---

```{r}
# Automating the preliminary data manipulation

createMatrices <- function(data, isHeader) {
  
  # Read in the initial data, specifying whether a header is present or not
  df <- read.csv(file= data, header = isHeader)
  
  # Convert the dataframe into a matrix in order to go forward with data manipulation
  lineups <- as.matrix(df)
  
  # Player interactions can be expressed in a matrix by multiplying the lineups by the transpose of the lineups
  transLineups <- t(lineups)
  playerInt <- transLineups %*% lineups
  
  # The points differential is the difference in points, divided by number of possessions, and then multiplied by 100
  
  # Use this following line until the differential code is complete
  #differential <- sample(-300:300, size = nrow(lineups), replace = TRUE)
  
  
  # First, we must determine the amount of points gained over how many possessions for each unique lineup 
  # Compare each line with the previous and set it as "y", as well as initialize the counter, possession, and points variable
  for (i in (nrow(lineups) - 1)) {
    y <- df[i,] - df[i + 1,]
    counter <- 0
    possession <- 0
    points <- 0
    
  # Then look at each individual column of y, which represents each individual player.  If a column is not equal to 0, it means that a change in the lineup has occurred.  Use the counter variable to keep track of whether this change has occurred.  If a counter does not equal 0, then a change in the lineup has happened between the past two possessions  
    for (j in (ncol(y) - 1)) {
      if (y[j] != 0) {
        counter = counter + 1
      }
      if (counter == 0) {
        possession <- possession + 1
        points <- points + y$point_diff
      } 
      else {
        
      }
  }
  differential <- df$point_diff
  difPerPlayer <- differential %*% lineups
  
  # The points differential per player is then turned into a 1 column matrix so further manipulation can be done
  matrixD <- matrix(difPerPlayer, ncol = 1) 
  
  # This library lets us take the pseudo inverse of a matrix, as we cannot take the inverse of a matrix that is not square, or has a determinant equal to 0.  This function also works if the matrix is square and/or has a determinant not equal to 0
  library(corpcor)
  psPlayerInt <- pseudoinverse(playerInt)
  
  # Multiplying the pseudo inverse by the differential per player gives us the values for our betas
  betas <- psPlayerInt %*% matrixD
  
  # The lineups multiplied by the betas gives us the predicted values for point differential
  predicted <- lineups %*% betas
  
  # We can then determine the approximate error by taking the difference between the predicted values and the differentials, squaring these differences, summing them up, and then dividing by the degrees of freedom
  difference <- differential - predicted
  differenceSquared <- difference ^ 2
  error <- sum(differenceSquared)
  
  # Combine the new variables into a list and return those for future access
  output <- list(betas, predicted, error)
  listNames <- c("Betas", "Predicted Values", "Approximate Error")
  names(output) <- listNames
  
  return(output)
}
```

```{r}
var <- createMatrices("C://Users/Brad Hymas/Desktop/point_diff_2019.csv", TRUE)
```