---
title: "WNBA Table Manipulation"
output: html_document
---
```{r}
## David Teuscher and Brad Hymas
## Last Edited: 14.06.2021
## This script fits models for APM and RAPM and calculates per game and per 36 minute statistics
## while preparing the data for use in a Shiny app
##########################################

# Load needed packages
library(tidyverse)
library(MASS)

# Change the year variable for different season assuming you have the player data and the matrix already created
# This was the only way to automate it due to errors in the play by play data
year <- 2019

# Create the filename string with the year given by the user
filename <- paste0("Data/point_diff_", year, "_updated.csv")
points <- read.csv(filename, header = TRUE)

# Set the y vector and X matrix
y <- points$point_diff
x <- points %>% dplyr::select(-point_diff, -game_id, -home_possession) %>% as.matrix()

# Fit an APM (multiple linear regression ) and a RAPM model (ridge regression) and extract the coefficients
ridge.model <- lm.ridge(y~-1+x, lambda = 2000)
model <- lm(y~-1+x)
ridge.coefs <- ridge.model$coef * 100
coefs <- model$coef * 100


# Determine the variance of the coefficients for both models
lm_var <- diag(vcov(model))* 1000
s2 <- 1/(nrow(x) - ncol(x)) * t(y - x %*% matrix(ridge.model$coef)) %*% (y - x %*% matrix(ridge.model$coef))
ridge_var_part1 <- solve(t(x) %*% x + 2000* diag(ncol(x))) %*% t(x) %*% x %*% solve(t(x) %*% x + 2000 * diag(ncol(x)))
ridge_var <- as.vector(s2) * diag(ridge_var_part1) * 1000

```

```{r}
# Per game stats
filename2 <- paste0("Data/Players_", year, ".csv")
player2019 <- read.csv(filename2)
# Remove columns that are not needed
player2019test <- player2019[,c(2, 4:6, 8:length(player2019))]


# The next section is adding in a lot of columns.
# The code is not the most efficient, but we did not have time to come back and make it more efficient
# Defensive rebounds per player
drb <- player2019test[1, 18] - player2019test[1, 17]
for (i in 2:nrow(player2019test)) {
  val <- player2019test[i, 18] - player2019test[i, 17]
  drb <- c(drb, val)
}

# Minutes played per game
mppg <- player2019test[1, 8] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 8] / player2019test[i, 6]
    mppg <- c(mppg, val)
}

# Field goals made per game
fgpg <- player2019test[1, 9] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 9] / player2019test[i, 6]
    fgpg <- c(fgpg, val)
}

# Field goals attempted per game
fgapg <- player2019test[1, 10] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 10] / player2019test[i, 6]
    fgapg <- c(fgapg, val)
}

# Two-pointers made per game
twoppg <- player2019test[1, 11] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 11] / player2019test[i, 6]
    twoppg <- c(twoppg, val)
}

# Two-pointers attempted per game
twopapg <- player2019test[1, 12] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 12] / player2019test[i, 6]
    twopapg <- c(twopapg, val)
}

# Three-pointers made per game
threeppg <- player2019test[1, 13] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 13] / player2019test[i, 6]
    threeppg <- c(threeppg, val)
}

# Three-pointers attempted per game
threepapg <- player2019test[1, 14] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 14] / player2019test[i, 6]
    threepapg <- c(threepapg, val)
}

# Free throws made per game
ftpg <- player2019test[1, 15] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 15] / player2019test[i, 6]
    ftpg <- c(ftpg, val)
}

# Free throws attempted per game
ftapg <- player2019test[1, 16] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 16] / player2019test[i, 6]
    ftapg <- c(ftapg, val)
}

# Offensive rebounds per game
orbpg <- player2019test[1, 17] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 17] / player2019test[i, 6]
    orbpg <- c(orbpg, val)
}

# Defensive rebounds per game
drbpg <- drb[1] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
  val <- drb[i] / player2019test[i, 6]
  drbpg <- c(drbpg, val)
}

# Total rebounds per game
trbpg <- player2019test[1, 18] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 18] / player2019test[i, 6]
    trbpg <- c(trbpg, val)
}

# Assists per game
apg <- player2019test[1, 19] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 19] / player2019test[i, 6]
    apg <- c(apg, val)
}

# Steals per game
spg <- player2019test[1, 20] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 20] / player2019test[i, 6]
    spg <- c(spg, val)
}

# Blocks per game
bpg <- player2019test[1, 21] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 21] / player2019test[i, 6]
    bpg <- c(bpg, val)
}

# Turnovers per game
tpg <- player2019test[1, 22] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 22] / player2019test[i, 6]
    tpg <- c(tpg, val)
}

# Personal fouls per game
pfpg <- player2019test[1, 23] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 23] / player2019test[i, 6]
    pfpg <- c(pfpg, val)
}

# Points per game
ppg <- player2019test[1, 24] / player2019test[1, 6]
for (i in 2:nrow(player2019test)) {
    val <- player2019test[i, 24] / player2019test[i, 6]
    ppg <- c(ppg, val)
}
```

```{r}
# This section adds variables based on the rate per 36 minutes played
# Again the code isn't the most efficient, but there are plans to make it more efficient
# Per 36 minutes stats

# Defensive rebounds per 36 minutes
drbm <- (drb / player2019test[,8]) * 36

# Field goals made per 36 minutes
fgm <- (player2019test[,9] / player2019test[,8]) * 36

# Field goals attempted per 36 minutes
fgam <- (player2019test[,10] / player2019test[,8]) * 36

# Two-pointers made per 36 minutes
twom <- (player2019test[,11] / player2019test[,8]) * 36

# Two-pointers attempted per 36 minutes
twoam <- (player2019test[,12] / player2019test[,8]) * 36

# Three-pointers made per 36 minutes
threem <- (player2019test[,13] / player2019test[,8]) * 36

# Three-pointers attempted per 36 minutes
threeam <- (player2019test[,14] / player2019test[,8]) * 36

# Free throws made per 36 minutes
ftm <- (player2019test[,15] / player2019test[,8]) * 36

# Free throws attempted per 36 minutes
ftam <- (player2019test[,16] / player2019test[,8]) * 36

# Offensive rebounds per 36 minutes
orbm <- (player2019test[,17] / player2019test[,8]) * 36

# Total rebounds per 36 minutes
trbm <- (player2019test[,18] / player2019test[,8]) * 36

# Assists per 36 minutes
am <- (player2019test[,19] / player2019test[,8]) * 36

# Steals per 36 minutes
sm <- (player2019test[,20] / player2019test[,8]) * 36

# Blocks per 36 minutes
bm <- (player2019test[,21] / player2019test[,8]) * 36

# Turnovers per 36 minutes
tm <- (player2019test[,22] / player2019test[,8]) * 36

# Personal fouls per 36 minutes
pfm <- (player2019test[,23] / player2019test[,8]) * 36

# Points per 36 minutes
pm <- (player2019test[,24] / player2019test[,8]) * 36

```

```{r}

# Adding per game data to columns 

player2019test['APG'] <- round(apg, digits = 3)
player2019test['BPG'] <- round(bpg, digits = 3)
player2019test['DRB'] <- round(drb, digits = 3)
player2019test['DRBPG'] <- round(drbpg, digits = 3)
player2019test['FGPG'] <- round(fgpg, digits = 3)
player2019test['FGAPG'] <- round(fgapg, digits = 3)
player2019test['FTPG'] <- round(ftpg, digits = 3)
player2019test['FTAPG'] <- round(ftapg, digits = 3)
player2019test['MPG'] <- round(mppg, digits = 3)
player2019test['ORBPG'] <- round(orbpg, digits = 3)
player2019test['PFPG'] <- round(pfpg, digits = 3)
player2019test['PPG'] <- round(ppg, digits = 3)
player2019test['SPG'] <- round(spg, digits = 3)
player2019test['X3PPG'] <- round(threeppg, digits = 3)
player2019test['X3PAPG'] <- round(threepapg, digits = 3)
player2019test['TPG'] <- round(tpg, digits = 3)
player2019test['TRBPG'] <- round(trbpg, digits = 3)
player2019test['X2PPG'] <- round(twoppg, digits = 3)
player2019test['X2PAPG'] <- round(twopapg, digits = 3)

# Adding per 36 minutes data to columns

player2019test['FGPM'] <- round(fgm, digits = 3)
player2019test['FGAPM'] <- round(fgam, digits = 3)
player2019test['X2PPM'] <- round(twom, digits = 3)
player2019test['X2PAPM'] <- round(twoam, digits = 3)
player2019test['X3PPM'] <- round(threem, digits = 3)
player2019test['X3PAPM'] <- round(threeam, digits = 3)
player2019test['FTPM'] <- round(ftm, digits = 3)
player2019test['FTAPM'] <- round(ftam, digits = 3)
player2019test['ORBPM'] <- round(orbm, digits = 3)
player2019test['TRBPM'] <- round(trbm, digits = 3)
player2019test['DRBPM'] <- round(drbm, digits = 3)
player2019test['ASPM'] <- round(am, digits = 3)
player2019test['SPM'] <- round(sm, digits = 3)
player2019test['BPM'] <- round(bm, digits = 3)
player2019test['TPM'] <- round(tm, digits = 3)
player2019test['PFPM'] <- round(pfm, digits = 3)
player2019test['PPM'] <- round(pm, digits = 3)

# Reorganize the columns so the per game columns are next to the corresponding season totals

player2019pg <- player2019test[, c(1:8, 38, 9, 34, 10, 35, 11, 47, 12, 48, 13, 43, 14, 44, 15, 36, 16, 37, 32, 33, 17, 39, 18, 46,
                                      19, 30, 20, 42, 21, 31, 22, 45, 23, 40, 24, 41, 25:29)]

# Reorganize the columns so the per 36 minutes columns are next to the corresponding season totals

player2019pm <- player2019test[, c(1:9, 49, 10, 50, 11, 51, 12, 52, 13, 53, 14, 54, 15, 55, 16, 56, 17, 57, 18, 58, 32, 59, 19, 60,
                                   20, 61, 21, 62, 22, 63, 23, 64, 24, 65)]
```

```{r}

# Add the coefficients from the base model and ridge regressed model to the table for both tables

player_2019_info_per_game <- player2019pg %>% arrange(Player) %>% mutate(APM = round(coefs, digits = 3), RAPM = round(ridge.coefs, digits = 3))
# Read in the salary data
filename3 <- paste0("Data/WNBA player salary ", year, "2.csv")
salaries <- read.csv(filename3)

# Join the salary to the player information with per game stats
players_2019_per_game <- player_2019_info_per_game %>% left_join(salaries %>% dplyr::select(Player, Salary), by = "Player")
# Write the file to a csv
#write.csv(players_2019_per_game, 'Data/shiny_data_per_game.csv')

# Join the salary to the player information with per 36 minutes stats
player_2019_info_per_minutes <- player2019pm %>% arrange(Player) %>% mutate(APM = round(coefs, digits = 3), RAPM = round(ridge.coefs, digits = 3))
players_2019_per_minutes <- player_2019_info_per_minutes %>% left_join(salaries %>% dplyr::select(Player, Salary), by = "Player")

# Write the file to a csv
write.csv(players_2019_per_minutes, 'Data/shiny_data_per_36.csv')

```